<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <Content Include="bin\Debug\net8.0\appsettings.Development.json" />
    <Content Include="bin\Debug\net8.0\appsettings.json" />
    <Content Include="bin\Debug\net8.0\Backend.deps.json" />
    <Content Include="bin\Debug\net8.0\Backend.runtimeconfig.json" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Agents.AI" Version="1.17.0" />
    <PackageReference Include="Microsoft.Agents.AI.OpenAI" Version="1.17.0" />
    <PackageReference Include="Microsoft.Extensions.AI.OpenAI" Version="10.8.3" />
    <PackageReference Include="ModelContextProtocol.AspNetCore" Version="2.1.0" />
    <PackageReference Include="Npgsql" Version="10.0.3" />
    <PackageReference Include="OpenAI" Version="2.12.0" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="6.6.2" />
  </ItemGroup>

  <ItemGroup>
    <None Include="bin\Debug\net8.0\Backend.dll" />
    <None Include="bin\Debug\net8.0\Backend.exe" />
    <None Include="bin\Debug\net8.0\Backend.pdb" />
    <None Include="bin\Debug\net8.0\Microsoft.OpenApi.dll" />
    <None Include="bin\Debug\net8.0\Npgsql.dll" />
    <None Include="bin\Debug\net8.0\Swashbuckle.AspNetCore.Swagger.dll" />
    <None Include="bin\Debug\net8.0\Swashbuckle.AspNetCore.SwaggerGen.dll" />
    <None Include="bin\Debug\net8.0\Swashbuckle.AspNetCore.SwaggerUI.dll" />
    <None Include="bin\Debug\net8.0\System.Diagnostics.DiagnosticSource.dll" />
  </ItemGroup>

</Project>
